In [35]:
import numpy as np

In [36]:
import array

In [37]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [38]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [39]:
np.array([1,2,3,4,5,"sudh" , 4+8j,])

array(['1', '2', '3', '4', '5', 'sudh', '(4+8j)'], dtype='<U64')

In [40]:
np.array([1,2,3,4.5,6.0])

array([1. , 2. , 3. , 4.5, 6. ])

In [41]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [42]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [43]:
np.array([[1,3],[3,4],[6,7,8]])

/tmp/ipykernel_5476/1655787997.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [44]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [45]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [46]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [47]:
arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [48]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [49]:
type(arr[0][0])

numpy.int32

In [50]:
type(arr[0][1])

numpy.int64

In [51]:
arr  = np.array([[1,3],[3,4]])

In [52]:
arr

array([[1, 3],
       [3, 4]])

In [53]:
type(arr[0][1])

numpy.int64

In [54]:
mat = np.matrix(arr)

In [55]:
mat

matrix([[1, 3],
        [3, 4]])

In [56]:
l = [3,4,5,76,7]

In [57]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [58]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [59]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [60]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [61]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [62]:
issubclass(np.ndarray,np.matrix )

False

In [63]:
arr

array([[1, 3],
       [3, 4]])

In [64]:
a = arr   #shallow copy

In [65]:
b = np.copy(arr) #deep copy

In [66]:
arr[0][0] = 67

In [67]:
arr = np.append(arr,[[5,6]],axis=0)

In [68]:
# c

In [69]:
arr

array([[67,  3],
       [ 3,  4],
       [ 5,  6]])

In [70]:
a

array([[67,  3],
       [ 3,  4]])

In [71]:
b

array([[1, 3],
       [3, 4]])

In [72]:
arr[-1]

array([5, 6])

In [73]:
for i in arr:
    print(i)

[67  3]
[3 4]
[5 6]


In [74]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [75]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [76]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [77]:
np.fromfunction(lambda i , j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [78]:
np.fromfunction(lambda i , j :i/j,(4,4))

/tmp/ipykernel_5476/3153817196.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(4,4))
/tmp/ipykernel_5476/3153817196.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [79]:
0/0

ZeroDivisionError: division by zero

In [80]:
1/0

ZeroDivisionError: division by zero

In [148]:
gen = (i*i for i in range(5))

In [149]:
def test(x):
    yield x 

In [150]:
test(5)

<generator object test at 0x7ff775092040>

In [151]:
gen
for i in gen :
    print(i)

0
1
4
9
16


In [152]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [153]:
np.fromstring('1,3,4,5,5' , sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [154]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

In [155]:
l = [3,4,5,6,7,8]

In [156]:
arr = np.array(l)

In [157]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [158]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [159]:
type(arr)

numpy.ndarray

In [160]:
arr1.ndim

2

In [161]:
arr1.size

12

In [162]:
arr1.shape


(3, 4)

In [163]:
arr1.dtype

dtype('int64')

In [164]:
arr

array([3, 4, 5, 6, 7, 8])

In [165]:
arr.size

6

In [166]:
arr.ndim

1

In [167]:
arr.shape

(6,)

In [168]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [169]:
arr2


array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [170]:
arr2.size

16

In [171]:
arr2.ndim

3

In [172]:
arr2.shape

(2, 2, 4)

In [173]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [174]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [175]:
arr4.ndim

4

In [176]:
arr4.shape

(1, 4, 2, 4)

In [177]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [257]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

In [181]:
np.arange(9,6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6, 6.3])

In [182]:
np.arange(1,10.1,2.25)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [183]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [184]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [185]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [186]:
np.ones(4)

array([1., 1., 1., 1.])

In [264]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [265]:
np.empty(5)

array([0.94673406, 0.39584253, 1.84342257, 0.5929227 , 0.32913134])

In [189]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [190]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [191]:
np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [268]:
np.logspace([2],[3] , axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [193]:
d = np.linspace(4,7,40)

In [194]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [195]:
d.ndim

1

In [196]:
d.shape

(40,)

In [197]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [198]:
d.reshape(4,2,5)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231],
        [4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769]],

       [[4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308],
        [5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385],
        [5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923]],

       [[6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462],
        [6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [199]:
np.logspace(2,5,10)


array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [200]:
np.random.rand(3)

array([0.76053669, 0.31000935, 0.3465412 ])

In [201]:
np.random.randn(5)

array([-0.94673406, -0.39584253, -1.84342257,  0.5929227 ,  0.32913134])

In [202]:
np.random.randn(2,2,3)

array([[[ 0.73189296,  0.16239589, -2.46194956],
        [ 0.78335922,  0.04411603,  1.84682848]],

       [[ 0.78303267, -0.14566981, -0.37713296],
        [ 0.99632107,  0.91670148,  0.75550492]]])

In [203]:
np.random.randint(5,60, (4,4))

array([[18, 12, 41, 41],
       [ 5, 48,  5, 50],
       [24, 50, 24,  6],
       [14, 34, 57, 48]])

In [204]:
np.random.randn(2,2,3)

array([[[-0.06700176,  0.71330326,  0.89051   ],
        [-1.52944607, -0.83746818, -0.63249511]],

       [[ 2.2962174 ,  0.68608397, -0.49516249],
        [-0.5345768 , -0.62957728, -0.27558463]]])

In [205]:
arr = np.random.randint(3,9, ( 3,3))

In [206]:
arr

array([[6, 5, 5],
       [3, 7, 3],
       [8, 5, 7]])

In [207]:
arr.reshape(1,9)

array([[6, 5, 5, 3, 7, 3, 8, 5, 7]])

In [208]:
arr.reshape(9,1)

array([[6],
       [5],
       [5],
       [3],
       [7],
       [3],
       [8],
       [5],
       [7]])

In [209]:
arr.reshape(1,1,9)

array([[[6, 5, 5, 3, 7, 3, 8, 5, 7]]])

In [210]:
arr.reshape(3,3,1)

array([[[6],
        [5],
        [5]],

       [[3],
        [7],
        [3]],

       [[8],
        [5],
        [7]]])

In [211]:
arr.reshape(3,-789654)

array([[6, 5, 5],
       [3, 7, 3],
       [8, 5, 7]])

In [212]:
arr.reshape(1,-256987)

array([[6, 5, 5, 3, 7, 3, 8, 5, 7]])

In [213]:
arr

array([[6, 5, 5],
       [3, 7, 3],
       [8, 5, 7]])

In [214]:
arr.max()

8

In [215]:
arr.min()

3

In [216]:
arr = np.random.randint(4,100, (5,5))

In [217]:
arr

array([[59, 60, 51, 72,  8],
       [22, 46, 21, 94, 76],
       [50, 15, 31, 31, 63],
       [11, 45, 69, 57, 76],
       [39,  7, 25, 46, 71]])

In [218]:
arr[3: , 3:]

array([[57, 76],
       [46, 71]])

In [219]:
arr[:,[1,3]]

array([[60, 72],
       [46, 94],
       [15, 31],
       [45, 57],
       [ 7, 46]])

In [220]:
arr

array([[59, 60, 51, 72,  8],
       [22, 46, 21, 94, 76],
       [50, 15, 31, 31, 63],
       [11, 45, 69, 57, 76],
       [39,  7, 25, 46, 71]])

In [221]:
arr[arr>10]

array([59, 60, 51, 72, 22, 46, 21, 94, 76, 50, 15, 31, 31, 63, 11, 45, 69,
       57, 76, 39, 25, 46, 71])

In [222]:
arr>10

array([[ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [223]:
arr

array([[59, 60, 51, 72,  8],
       [22, 46, 21, 94, 76],
       [50, 15, 31, 31, 63],
       [11, 45, 69, 57, 76],
       [39,  7, 25, 46, 71]])

In [224]:
arr * arr

array([[3481, 3600, 2601, 5184,   64],
       [ 484, 2116,  441, 8836, 5776],
       [2500,  225,  961,  961, 3969],
       [ 121, 2025, 4761, 3249, 5776],
       [1521,   49,  625, 2116, 5041]])

In [225]:
arr1 = np.random.randint(2,4,(3,3))

In [226]:
arr2 = np.random.randint(2,4,(3,3))

In [227]:
arr1

array([[2, 2, 3],
       [3, 2, 2],
       [2, 2, 2]])

In [228]:
arr2

array([[3, 2, 3],
       [3, 3, 2],
       [2, 2, 2]])

In [229]:
arr1*arr2 # element by element

array([[6, 4, 9],
       [9, 6, 4],
       [4, 4, 4]])

In [230]:
arr1@arr2 #matrix ,multiplication

array([[18, 16, 16],
       [19, 16, 17],
       [16, 14, 14]])

In [231]:
arr/0

/tmp/ipykernel_5476/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [232]:
arr**2

array([[3481, 3600, 2601, 5184,   64],
       [ 484, 2116,  441, 8836, 5776],
       [2500,  225,  961,  961, 3969],
       [ 121, 2025, 4761, 3249, 5776],
       [1521,   49,  625, 2116, 5041]])

In [233]:
arr = np.zeros((3,4))

In [234]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [235]:
a = np.array([1,2,3,5])

In [236]:
a


array([1, 2, 3, 5])

In [237]:
arr + a 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [238]:
arr+ 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [239]:
b = np.array([5,6,7])

In [240]:
b

array([5, 6, 7])

In [241]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [242]:
b

array([5, 6, 7])

In [243]:
b = np.array([[5,6,7]])

In [244]:
b.T

array([[5],
       [6],
       [7]])

In [245]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [246]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [247]:
arr = np.random.rand(5,4)

In [248]:
arr

array([[0.2550368 , 0.99330372, 0.70638753, 0.65790969],
       [0.90261031, 0.3711546 , 0.05965088, 0.27463413],
       [0.75970234, 0.57655497, 0.90995341, 0.28058961],
       [0.60035149, 0.52247159, 0.95425239, 0.74984602],
       [0.41242653, 0.56164441, 0.23988026, 0.2617863 ]])

In [249]:
np.sqrt(arr)

array([[0.50501168, 0.99664624, 0.84046864, 0.81111632],
       [0.95005806, 0.60922459, 0.24423529, 0.52405547],
       [0.87160905, 0.75931217, 0.95391478, 0.5297071 ],
       [0.77482352, 0.72282196, 0.97685843, 0.8659365 ],
       [0.64220443, 0.74942939, 0.48977572, 0.51165056]])

In [250]:
np.exp(arr)

array([[1.29050911, 2.70014027, 2.02665678, 1.93075224],
       [2.46603183, 1.44940714, 1.0614659 , 1.31604909],
       [2.13763984, 1.77989605, 2.4842068 , 1.32391018],
       [1.82275937, 1.68619007, 2.59672851, 2.11667406],
       [1.51047857, 1.75355369, 1.27109694, 1.29924886]])

In [251]:
np.log10(arr)

array([[-0.59339716, -0.00291794, -0.15095698, -0.18183372],
       [-0.04449971, -0.43044515, -1.22438315, -0.56124549],
       [-0.11935653, -0.23915928, -0.04098084, -0.55192841],
       [-0.22159441, -0.28193732, -0.02033674, -0.12502791],
       [-0.3846534 , -0.25053856, -0.6200055 , -0.58205309]])

In [252]:
arr1 = np.random.randint(2,5, (5,5))

In [253]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.47712125, 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.60205999, 0.60205999, 0.30103   ],
       [0.30103   , 0.47712125, 0.60205999, 0.30103   , 0.30103   ],
       [0.47712125, 0.30103   , 0.30103   , 0.30103   , 0.47712125],
       [0.60205999, 0.47712125, 0.47712125, 0.47712125, 0.47712125]])

In [254]:
arr1

array([[4, 4, 3, 2, 3],
       [2, 3, 4, 4, 2],
       [2, 3, 4, 2, 2],
       [3, 2, 2, 2, 3],
       [4, 3, 3, 3, 3]])

In [255]:
np.random.seed(13)

In [256]:
np.random.seed(50) #generate same random numbers
np.random.rand(2,4)

array([[0.49460165, 0.2280831 , 0.25547392, 0.39632991],
       [0.3773151 , 0.99657423, 0.4081972 , 0.77189399]])